//===- Passes.h - AliasMetaPropagation passes --------------------*- C++ -*-===//
//
// Public header for the alias metadata propagation passes.
//
//===----------------------------------------------------------------------===//
#ifndef ALIASMETAPROPAGATION_PASSES_H
#define ALIASMETAPROPAGATION_PASSES_H

#include "mlir/Pass/Pass.h"
#include <memory>

namespace mlir {
class ModuleOp;

namespace alias_meta {

// ---------- Discardable attribute names used between Pass 1 and Pass 2 ------
//
// These are simple string-keyed discardable attributes — no custom dialect
// registration needed. Pass 1 writes them; Pass 2 reads and removes them.

/// Attribute on memref.load / memref.store indicating alias-group membership.
/// Value is an IntegerAttr (i32) giving the group ID.
/// Convention: even group IDs = "lo" subview, odd = "hi" subview of the same
/// pair. So pair N has lo = 2*N, hi = 2*N+1.
constexpr llvm::StringLiteral kAliasGroupAttr = "alias_meta.group_id";

/// Attribute on memref.load / memref.store indicating which role in the pair.
/// Value is a StringAttr: "lo" or "hi".
constexpr llvm::StringLiteral kAliasRoleAttr = "alias_meta.role";

/// Attribute on func.call indicating disjoint argument pairs for noinline case.
/// Value is an ArrayAttr of DenseI32ArrayAttr pairs [[lo_idx, hi_idx], ...].
constexpr llvm::StringLiteral kDisjointArgsAttr = "alias_meta.disjoint_args";

// ---------- Pass declarations (generated by TableGen) -----------------------

#define GEN_PASS_DECL
#include "AliasMetaPropagation/Passes.h.inc"

// ---------- Pass registration -----------------------------------------------

#define GEN_PASS_REGISTRATION
#include "AliasMetaPropagation/Passes.h.inc"

} // namespace alias_meta
} // namespace mlir

#endif // ALIASMETAPROPAGATION_PASSES_H
